;; Generated by :claw at 2021-08-09T23:33:55.735138+03:00
(asdf:defsystem #:aw-imgui-bindings
  :description "Bindings generated by aw-imgui"
  :author "CLAW"
  :license "Public domain"
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi :iffi :claw-utils)
  :components
  ((:file "bindings/x86_64-pc-linux-gnu" :if-feature
    (:and :x86-64 :linux))
   (:file "bindings/aarch64-linux-android" :if-feature
    (:and :aarch64 :android))))